'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.21006.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Countries
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Caps.Console.Countries", GetType(Countries).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Andorra.
        '''</summary>
        Friend Shared ReadOnly Property cc_AD() As String
            Get
                Return ResourceManager.GetString("cc_AD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to United Arab Emirates.
        '''</summary>
        Friend Shared ReadOnly Property cc_AE() As String
            Get
                Return ResourceManager.GetString("cc_AE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Afghanistan.
        '''</summary>
        Friend Shared ReadOnly Property cc_AF() As String
            Get
                Return ResourceManager.GetString("cc_AF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Antigua and Barbuda.
        '''</summary>
        Friend Shared ReadOnly Property cc_AG() As String
            Get
                Return ResourceManager.GetString("cc_AG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Anguilla.
        '''</summary>
        Friend Shared ReadOnly Property cc_AI() As String
            Get
                Return ResourceManager.GetString("cc_AI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Albania.
        '''</summary>
        Friend Shared ReadOnly Property cc_AL() As String
            Get
                Return ResourceManager.GetString("cc_AL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Armenia.
        '''</summary>
        Friend Shared ReadOnly Property cc_AM() As String
            Get
                Return ResourceManager.GetString("cc_AM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Netherlands Antilles.
        '''</summary>
        Friend Shared ReadOnly Property cc_AN() As String
            Get
                Return ResourceManager.GetString("cc_AN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Angola.
        '''</summary>
        Friend Shared ReadOnly Property cc_AO() As String
            Get
                Return ResourceManager.GetString("cc_AO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Antarctica.
        '''</summary>
        Friend Shared ReadOnly Property cc_AQ() As String
            Get
                Return ResourceManager.GetString("cc_AQ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Argentina.
        '''</summary>
        Friend Shared ReadOnly Property cc_AR() As String
            Get
                Return ResourceManager.GetString("cc_AR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to American Samoa.
        '''</summary>
        Friend Shared ReadOnly Property cc_AS() As String
            Get
                Return ResourceManager.GetString("cc_AS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Austria.
        '''</summary>
        Friend Shared ReadOnly Property cc_AT() As String
            Get
                Return ResourceManager.GetString("cc_AT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Australia.
        '''</summary>
        Friend Shared ReadOnly Property cc_AU() As String
            Get
                Return ResourceManager.GetString("cc_AU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aruba.
        '''</summary>
        Friend Shared ReadOnly Property cc_AW() As String
            Get
                Return ResourceManager.GetString("cc_AW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Åland Islands.
        '''</summary>
        Friend Shared ReadOnly Property cc_AX() As String
            Get
                Return ResourceManager.GetString("cc_AX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Azerbaijan.
        '''</summary>
        Friend Shared ReadOnly Property cc_AZ() As String
            Get
                Return ResourceManager.GetString("cc_AZ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bosnia and Herzegovina.
        '''</summary>
        Friend Shared ReadOnly Property cc_BA() As String
            Get
                Return ResourceManager.GetString("cc_BA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Barbados.
        '''</summary>
        Friend Shared ReadOnly Property cc_BB() As String
            Get
                Return ResourceManager.GetString("cc_BB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bangladesh.
        '''</summary>
        Friend Shared ReadOnly Property cc_BD() As String
            Get
                Return ResourceManager.GetString("cc_BD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Belgium.
        '''</summary>
        Friend Shared ReadOnly Property cc_BE() As String
            Get
                Return ResourceManager.GetString("cc_BE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Burkina Faso.
        '''</summary>
        Friend Shared ReadOnly Property cc_BF() As String
            Get
                Return ResourceManager.GetString("cc_BF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bulgaria.
        '''</summary>
        Friend Shared ReadOnly Property cc_BG() As String
            Get
                Return ResourceManager.GetString("cc_BG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bahrain.
        '''</summary>
        Friend Shared ReadOnly Property cc_BH() As String
            Get
                Return ResourceManager.GetString("cc_BH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Burundi.
        '''</summary>
        Friend Shared ReadOnly Property cc_BI() As String
            Get
                Return ResourceManager.GetString("cc_BI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Benin.
        '''</summary>
        Friend Shared ReadOnly Property cc_BJ() As String
            Get
                Return ResourceManager.GetString("cc_BJ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Saint Barthélemy.
        '''</summary>
        Friend Shared ReadOnly Property cc_BL() As String
            Get
                Return ResourceManager.GetString("cc_BL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bermuda.
        '''</summary>
        Friend Shared ReadOnly Property cc_BM() As String
            Get
                Return ResourceManager.GetString("cc_BM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Brunei.
        '''</summary>
        Friend Shared ReadOnly Property cc_BN() As String
            Get
                Return ResourceManager.GetString("cc_BN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bolivia.
        '''</summary>
        Friend Shared ReadOnly Property cc_BO() As String
            Get
                Return ResourceManager.GetString("cc_BO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Brazil.
        '''</summary>
        Friend Shared ReadOnly Property cc_BR() As String
            Get
                Return ResourceManager.GetString("cc_BR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bahamas.
        '''</summary>
        Friend Shared ReadOnly Property cc_BS() As String
            Get
                Return ResourceManager.GetString("cc_BS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bhutan.
        '''</summary>
        Friend Shared ReadOnly Property cc_BT() As String
            Get
                Return ResourceManager.GetString("cc_BT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bouvet Island.
        '''</summary>
        Friend Shared ReadOnly Property cc_BV() As String
            Get
                Return ResourceManager.GetString("cc_BV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Botswana.
        '''</summary>
        Friend Shared ReadOnly Property cc_BW() As String
            Get
                Return ResourceManager.GetString("cc_BW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Belarus.
        '''</summary>
        Friend Shared ReadOnly Property cc_BY() As String
            Get
                Return ResourceManager.GetString("cc_BY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Belize.
        '''</summary>
        Friend Shared ReadOnly Property cc_BZ() As String
            Get
                Return ResourceManager.GetString("cc_BZ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Canada.
        '''</summary>
        Friend Shared ReadOnly Property cc_CA() As String
            Get
                Return ResourceManager.GetString("cc_CA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cocos Islands.
        '''</summary>
        Friend Shared ReadOnly Property cc_CC() As String
            Get
                Return ResourceManager.GetString("cc_CC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Congo - Zaire.
        '''</summary>
        Friend Shared ReadOnly Property cc_CD() As String
            Get
                Return ResourceManager.GetString("cc_CD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Central Africa.
        '''</summary>
        Friend Shared ReadOnly Property cc_CF() As String
            Get
                Return ResourceManager.GetString("cc_CF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Congo.
        '''</summary>
        Friend Shared ReadOnly Property cc_CG() As String
            Get
                Return ResourceManager.GetString("cc_CG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Switzerland.
        '''</summary>
        Friend Shared ReadOnly Property cc_CH() As String
            Get
                Return ResourceManager.GetString("cc_CH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ivory Coast.
        '''</summary>
        Friend Shared ReadOnly Property cc_CI() As String
            Get
                Return ResourceManager.GetString("cc_CI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cook Islands.
        '''</summary>
        Friend Shared ReadOnly Property cc_CK() As String
            Get
                Return ResourceManager.GetString("cc_CK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chile.
        '''</summary>
        Friend Shared ReadOnly Property cc_CL() As String
            Get
                Return ResourceManager.GetString("cc_CL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cameroon.
        '''</summary>
        Friend Shared ReadOnly Property cc_CM() As String
            Get
                Return ResourceManager.GetString("cc_CM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to China.
        '''</summary>
        Friend Shared ReadOnly Property cc_CN() As String
            Get
                Return ResourceManager.GetString("cc_CN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Colombia.
        '''</summary>
        Friend Shared ReadOnly Property cc_CO() As String
            Get
                Return ResourceManager.GetString("cc_CO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Costa Rica.
        '''</summary>
        Friend Shared ReadOnly Property cc_CR() As String
            Get
                Return ResourceManager.GetString("cc_CR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cuba.
        '''</summary>
        Friend Shared ReadOnly Property cc_CU() As String
            Get
                Return ResourceManager.GetString("cc_CU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cape Verde.
        '''</summary>
        Friend Shared ReadOnly Property cc_CV() As String
            Get
                Return ResourceManager.GetString("cc_CV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Christmas Island.
        '''</summary>
        Friend Shared ReadOnly Property cc_CX() As String
            Get
                Return ResourceManager.GetString("cc_CX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cyprus.
        '''</summary>
        Friend Shared ReadOnly Property cc_CY() As String
            Get
                Return ResourceManager.GetString("cc_CY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Czech Republic.
        '''</summary>
        Friend Shared ReadOnly Property cc_CZ() As String
            Get
                Return ResourceManager.GetString("cc_CZ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Germany.
        '''</summary>
        Friend Shared ReadOnly Property cc_DE() As String
            Get
                Return ResourceManager.GetString("cc_DE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Djibouti.
        '''</summary>
        Friend Shared ReadOnly Property cc_DJ() As String
            Get
                Return ResourceManager.GetString("cc_DJ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Denmark.
        '''</summary>
        Friend Shared ReadOnly Property cc_DK() As String
            Get
                Return ResourceManager.GetString("cc_DK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dominica.
        '''</summary>
        Friend Shared ReadOnly Property cc_DM() As String
            Get
                Return ResourceManager.GetString("cc_DM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dominican Republic.
        '''</summary>
        Friend Shared ReadOnly Property cc_DO() As String
            Get
                Return ResourceManager.GetString("cc_DO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Algeria.
        '''</summary>
        Friend Shared ReadOnly Property cc_DZ() As String
            Get
                Return ResourceManager.GetString("cc_DZ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ecuador.
        '''</summary>
        Friend Shared ReadOnly Property cc_EC() As String
            Get
                Return ResourceManager.GetString("cc_EC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Estonia.
        '''</summary>
        Friend Shared ReadOnly Property cc_EE() As String
            Get
                Return ResourceManager.GetString("cc_EE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Egypt.
        '''</summary>
        Friend Shared ReadOnly Property cc_EG() As String
            Get
                Return ResourceManager.GetString("cc_EG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Western Sahara.
        '''</summary>
        Friend Shared ReadOnly Property cc_EH() As String
            Get
                Return ResourceManager.GetString("cc_EH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Eritrea.
        '''</summary>
        Friend Shared ReadOnly Property cc_ER() As String
            Get
                Return ResourceManager.GetString("cc_ER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Spain.
        '''</summary>
        Friend Shared ReadOnly Property cc_ES() As String
            Get
                Return ResourceManager.GetString("cc_ES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ethiopia.
        '''</summary>
        Friend Shared ReadOnly Property cc_ET() As String
            Get
                Return ResourceManager.GetString("cc_ET", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Finland.
        '''</summary>
        Friend Shared ReadOnly Property cc_FI() As String
            Get
                Return ResourceManager.GetString("cc_FI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fiji.
        '''</summary>
        Friend Shared ReadOnly Property cc_FJ() As String
            Get
                Return ResourceManager.GetString("cc_FJ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Falkland Islands.
        '''</summary>
        Friend Shared ReadOnly Property cc_FK() As String
            Get
                Return ResourceManager.GetString("cc_FK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Micronesia.
        '''</summary>
        Friend Shared ReadOnly Property cc_FM() As String
            Get
                Return ResourceManager.GetString("cc_FM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Faroe Islands.
        '''</summary>
        Friend Shared ReadOnly Property cc_FO() As String
            Get
                Return ResourceManager.GetString("cc_FO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to France.
        '''</summary>
        Friend Shared ReadOnly Property cc_FR() As String
            Get
                Return ResourceManager.GetString("cc_FR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gabon.
        '''</summary>
        Friend Shared ReadOnly Property cc_GA() As String
            Get
                Return ResourceManager.GetString("cc_GA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to United Kingdom.
        '''</summary>
        Friend Shared ReadOnly Property cc_GB() As String
            Get
                Return ResourceManager.GetString("cc_GB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Grenada.
        '''</summary>
        Friend Shared ReadOnly Property cc_GD() As String
            Get
                Return ResourceManager.GetString("cc_GD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Georgia.
        '''</summary>
        Friend Shared ReadOnly Property cc_GE() As String
            Get
                Return ResourceManager.GetString("cc_GE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to French Guiana.
        '''</summary>
        Friend Shared ReadOnly Property cc_GF() As String
            Get
                Return ResourceManager.GetString("cc_GF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Guernsey.
        '''</summary>
        Friend Shared ReadOnly Property cc_GG() As String
            Get
                Return ResourceManager.GetString("cc_GG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ghana.
        '''</summary>
        Friend Shared ReadOnly Property cc_GH() As String
            Get
                Return ResourceManager.GetString("cc_GH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gibraltar.
        '''</summary>
        Friend Shared ReadOnly Property cc_GI() As String
            Get
                Return ResourceManager.GetString("cc_GI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Greenland.
        '''</summary>
        Friend Shared ReadOnly Property cc_GL() As String
            Get
                Return ResourceManager.GetString("cc_GL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gambia.
        '''</summary>
        Friend Shared ReadOnly Property cc_GM() As String
            Get
                Return ResourceManager.GetString("cc_GM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Guinea.
        '''</summary>
        Friend Shared ReadOnly Property cc_GN() As String
            Get
                Return ResourceManager.GetString("cc_GN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Guadeloupe.
        '''</summary>
        Friend Shared ReadOnly Property cc_GP() As String
            Get
                Return ResourceManager.GetString("cc_GP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Equatorial Guinea.
        '''</summary>
        Friend Shared ReadOnly Property cc_GQ() As String
            Get
                Return ResourceManager.GetString("cc_GQ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Greece.
        '''</summary>
        Friend Shared ReadOnly Property cc_GR() As String
            Get
                Return ResourceManager.GetString("cc_GR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to South Georgia and South Sandwich Islands.
        '''</summary>
        Friend Shared ReadOnly Property cc_GS() As String
            Get
                Return ResourceManager.GetString("cc_GS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Guatemala.
        '''</summary>
        Friend Shared ReadOnly Property cc_GT() As String
            Get
                Return ResourceManager.GetString("cc_GT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Guam.
        '''</summary>
        Friend Shared ReadOnly Property cc_GU() As String
            Get
                Return ResourceManager.GetString("cc_GU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Guinea-Bissau.
        '''</summary>
        Friend Shared ReadOnly Property cc_GW() As String
            Get
                Return ResourceManager.GetString("cc_GW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Guyana.
        '''</summary>
        Friend Shared ReadOnly Property cc_GY() As String
            Get
                Return ResourceManager.GetString("cc_GY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hong Kong.
        '''</summary>
        Friend Shared ReadOnly Property cc_HK() As String
            Get
                Return ResourceManager.GetString("cc_HK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Heard Island and McDonald Islands.
        '''</summary>
        Friend Shared ReadOnly Property cc_HM() As String
            Get
                Return ResourceManager.GetString("cc_HM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Honduras.
        '''</summary>
        Friend Shared ReadOnly Property cc_HN() As String
            Get
                Return ResourceManager.GetString("cc_HN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Croatia.
        '''</summary>
        Friend Shared ReadOnly Property cc_HR() As String
            Get
                Return ResourceManager.GetString("cc_HR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Haiti.
        '''</summary>
        Friend Shared ReadOnly Property cc_HT() As String
            Get
                Return ResourceManager.GetString("cc_HT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hungary.
        '''</summary>
        Friend Shared ReadOnly Property cc_HU() As String
            Get
                Return ResourceManager.GetString("cc_HU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Indonesia.
        '''</summary>
        Friend Shared ReadOnly Property cc_ID() As String
            Get
                Return ResourceManager.GetString("cc_ID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ireland.
        '''</summary>
        Friend Shared ReadOnly Property cc_IE() As String
            Get
                Return ResourceManager.GetString("cc_IE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Israel.
        '''</summary>
        Friend Shared ReadOnly Property cc_IL() As String
            Get
                Return ResourceManager.GetString("cc_IL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Isle of Man.
        '''</summary>
        Friend Shared ReadOnly Property cc_IM() As String
            Get
                Return ResourceManager.GetString("cc_IM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to India.
        '''</summary>
        Friend Shared ReadOnly Property cc_IN() As String
            Get
                Return ResourceManager.GetString("cc_IN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to British Indian Ocean Territory.
        '''</summary>
        Friend Shared ReadOnly Property cc_IO() As String
            Get
                Return ResourceManager.GetString("cc_IO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Iraq.
        '''</summary>
        Friend Shared ReadOnly Property cc_IQ() As String
            Get
                Return ResourceManager.GetString("cc_IQ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Iran.
        '''</summary>
        Friend Shared ReadOnly Property cc_IR() As String
            Get
                Return ResourceManager.GetString("cc_IR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Iceland.
        '''</summary>
        Friend Shared ReadOnly Property cc_IS() As String
            Get
                Return ResourceManager.GetString("cc_IS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Italy.
        '''</summary>
        Friend Shared ReadOnly Property cc_IT() As String
            Get
                Return ResourceManager.GetString("cc_IT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jersey.
        '''</summary>
        Friend Shared ReadOnly Property cc_JE() As String
            Get
                Return ResourceManager.GetString("cc_JE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jamaica.
        '''</summary>
        Friend Shared ReadOnly Property cc_JM() As String
            Get
                Return ResourceManager.GetString("cc_JM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jordan.
        '''</summary>
        Friend Shared ReadOnly Property cc_JO() As String
            Get
                Return ResourceManager.GetString("cc_JO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Japan.
        '''</summary>
        Friend Shared ReadOnly Property cc_JP() As String
            Get
                Return ResourceManager.GetString("cc_JP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kenya.
        '''</summary>
        Friend Shared ReadOnly Property cc_KE() As String
            Get
                Return ResourceManager.GetString("cc_KE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kyrgyzstan.
        '''</summary>
        Friend Shared ReadOnly Property cc_KG() As String
            Get
                Return ResourceManager.GetString("cc_KG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cambodia.
        '''</summary>
        Friend Shared ReadOnly Property cc_KH() As String
            Get
                Return ResourceManager.GetString("cc_KH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kiribati.
        '''</summary>
        Friend Shared ReadOnly Property cc_KI() As String
            Get
                Return ResourceManager.GetString("cc_KI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Comoros.
        '''</summary>
        Friend Shared ReadOnly Property cc_KM() As String
            Get
                Return ResourceManager.GetString("cc_KM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Saint Kitts and Nevis.
        '''</summary>
        Friend Shared ReadOnly Property cc_KN() As String
            Get
                Return ResourceManager.GetString("cc_KN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nort Korea.
        '''</summary>
        Friend Shared ReadOnly Property cc_KP() As String
            Get
                Return ResourceManager.GetString("cc_KP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to South Korea.
        '''</summary>
        Friend Shared ReadOnly Property cc_KR() As String
            Get
                Return ResourceManager.GetString("cc_KR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kuwait.
        '''</summary>
        Friend Shared ReadOnly Property cc_KW() As String
            Get
                Return ResourceManager.GetString("cc_KW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cayman Islands.
        '''</summary>
        Friend Shared ReadOnly Property cc_KY() As String
            Get
                Return ResourceManager.GetString("cc_KY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kazakhstan.
        '''</summary>
        Friend Shared ReadOnly Property cc_KZ() As String
            Get
                Return ResourceManager.GetString("cc_KZ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Laos.
        '''</summary>
        Friend Shared ReadOnly Property cc_LA() As String
            Get
                Return ResourceManager.GetString("cc_LA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lebanon.
        '''</summary>
        Friend Shared ReadOnly Property cc_LB() As String
            Get
                Return ResourceManager.GetString("cc_LB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Saint Lucia.
        '''</summary>
        Friend Shared ReadOnly Property cc_LC() As String
            Get
                Return ResourceManager.GetString("cc_LC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Liechtenstein.
        '''</summary>
        Friend Shared ReadOnly Property cc_LI() As String
            Get
                Return ResourceManager.GetString("cc_LI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sri Lanka.
        '''</summary>
        Friend Shared ReadOnly Property cc_LK() As String
            Get
                Return ResourceManager.GetString("cc_LK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Liberia.
        '''</summary>
        Friend Shared ReadOnly Property cc_LR() As String
            Get
                Return ResourceManager.GetString("cc_LR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lesotho.
        '''</summary>
        Friend Shared ReadOnly Property cc_LS() As String
            Get
                Return ResourceManager.GetString("cc_LS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lithuania.
        '''</summary>
        Friend Shared ReadOnly Property cc_LT() As String
            Get
                Return ResourceManager.GetString("cc_LT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Luxembourg.
        '''</summary>
        Friend Shared ReadOnly Property cc_LU() As String
            Get
                Return ResourceManager.GetString("cc_LU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Latvia.
        '''</summary>
        Friend Shared ReadOnly Property cc_LV() As String
            Get
                Return ResourceManager.GetString("cc_LV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Libya.
        '''</summary>
        Friend Shared ReadOnly Property cc_LY() As String
            Get
                Return ResourceManager.GetString("cc_LY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Morocco.
        '''</summary>
        Friend Shared ReadOnly Property cc_MA() As String
            Get
                Return ResourceManager.GetString("cc_MA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Monaco.
        '''</summary>
        Friend Shared ReadOnly Property cc_MC() As String
            Get
                Return ResourceManager.GetString("cc_MC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Moldova.
        '''</summary>
        Friend Shared ReadOnly Property cc_MD() As String
            Get
                Return ResourceManager.GetString("cc_MD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Montenegro.
        '''</summary>
        Friend Shared ReadOnly Property cc_ME() As String
            Get
                Return ResourceManager.GetString("cc_ME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Saint Martin.
        '''</summary>
        Friend Shared ReadOnly Property cc_MF() As String
            Get
                Return ResourceManager.GetString("cc_MF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Madagascar.
        '''</summary>
        Friend Shared ReadOnly Property cc_MG() As String
            Get
                Return ResourceManager.GetString("cc_MG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Marshall Islands.
        '''</summary>
        Friend Shared ReadOnly Property cc_MH() As String
            Get
                Return ResourceManager.GetString("cc_MH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Macedonia.
        '''</summary>
        Friend Shared ReadOnly Property cc_MK() As String
            Get
                Return ResourceManager.GetString("cc_MK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mali.
        '''</summary>
        Friend Shared ReadOnly Property cc_ML() As String
            Get
                Return ResourceManager.GetString("cc_ML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Myanmar.
        '''</summary>
        Friend Shared ReadOnly Property cc_MM() As String
            Get
                Return ResourceManager.GetString("cc_MM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mongolia.
        '''</summary>
        Friend Shared ReadOnly Property cc_MN() As String
            Get
                Return ResourceManager.GetString("cc_MN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Macao.
        '''</summary>
        Friend Shared ReadOnly Property cc_MO() As String
            Get
                Return ResourceManager.GetString("cc_MO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Northern Marianas.
        '''</summary>
        Friend Shared ReadOnly Property cc_MP() As String
            Get
                Return ResourceManager.GetString("cc_MP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Martinique.
        '''</summary>
        Friend Shared ReadOnly Property cc_MQ() As String
            Get
                Return ResourceManager.GetString("cc_MQ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mauritania.
        '''</summary>
        Friend Shared ReadOnly Property cc_MR() As String
            Get
                Return ResourceManager.GetString("cc_MR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Montserrat.
        '''</summary>
        Friend Shared ReadOnly Property cc_MS() As String
            Get
                Return ResourceManager.GetString("cc_MS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Malta.
        '''</summary>
        Friend Shared ReadOnly Property cc_MT() As String
            Get
                Return ResourceManager.GetString("cc_MT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mauritius.
        '''</summary>
        Friend Shared ReadOnly Property cc_MU() As String
            Get
                Return ResourceManager.GetString("cc_MU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Maldives.
        '''</summary>
        Friend Shared ReadOnly Property cc_MV() As String
            Get
                Return ResourceManager.GetString("cc_MV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Malawi.
        '''</summary>
        Friend Shared ReadOnly Property cc_MW() As String
            Get
                Return ResourceManager.GetString("cc_MW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mexico.
        '''</summary>
        Friend Shared ReadOnly Property cc_MX() As String
            Get
                Return ResourceManager.GetString("cc_MX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Malaysia.
        '''</summary>
        Friend Shared ReadOnly Property cc_MY() As String
            Get
                Return ResourceManager.GetString("cc_MY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mozambique.
        '''</summary>
        Friend Shared ReadOnly Property cc_MZ() As String
            Get
                Return ResourceManager.GetString("cc_MZ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Namibia.
        '''</summary>
        Friend Shared ReadOnly Property cc_NA() As String
            Get
                Return ResourceManager.GetString("cc_NA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Caledonia.
        '''</summary>
        Friend Shared ReadOnly Property cc_NC() As String
            Get
                Return ResourceManager.GetString("cc_NC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Niger.
        '''</summary>
        Friend Shared ReadOnly Property cc_NE() As String
            Get
                Return ResourceManager.GetString("cc_NE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Norfolk Island.
        '''</summary>
        Friend Shared ReadOnly Property cc_NF() As String
            Get
                Return ResourceManager.GetString("cc_NF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nigeria.
        '''</summary>
        Friend Shared ReadOnly Property cc_NG() As String
            Get
                Return ResourceManager.GetString("cc_NG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nicaragua.
        '''</summary>
        Friend Shared ReadOnly Property cc_NI() As String
            Get
                Return ResourceManager.GetString("cc_NI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Netherlands.
        '''</summary>
        Friend Shared ReadOnly Property cc_NL() As String
            Get
                Return ResourceManager.GetString("cc_NL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Norway.
        '''</summary>
        Friend Shared ReadOnly Property cc_NO() As String
            Get
                Return ResourceManager.GetString("cc_NO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nepal.
        '''</summary>
        Friend Shared ReadOnly Property cc_NP() As String
            Get
                Return ResourceManager.GetString("cc_NP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nauru.
        '''</summary>
        Friend Shared ReadOnly Property cc_NR() As String
            Get
                Return ResourceManager.GetString("cc_NR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Niue.
        '''</summary>
        Friend Shared ReadOnly Property cc_NU() As String
            Get
                Return ResourceManager.GetString("cc_NU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Zealand.
        '''</summary>
        Friend Shared ReadOnly Property cc_NZ() As String
            Get
                Return ResourceManager.GetString("cc_NZ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Oman.
        '''</summary>
        Friend Shared ReadOnly Property cc_OM() As String
            Get
                Return ResourceManager.GetString("cc_OM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Panama.
        '''</summary>
        Friend Shared ReadOnly Property cc_PA() As String
            Get
                Return ResourceManager.GetString("cc_PA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Peru.
        '''</summary>
        Friend Shared ReadOnly Property cc_PE() As String
            Get
                Return ResourceManager.GetString("cc_PE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to French Polynesia.
        '''</summary>
        Friend Shared ReadOnly Property cc_PF() As String
            Get
                Return ResourceManager.GetString("cc_PF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Papua New Guinea.
        '''</summary>
        Friend Shared ReadOnly Property cc_PG() As String
            Get
                Return ResourceManager.GetString("cc_PG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Philippines.
        '''</summary>
        Friend Shared ReadOnly Property cc_PH() As String
            Get
                Return ResourceManager.GetString("cc_PH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pakistan.
        '''</summary>
        Friend Shared ReadOnly Property cc_PK() As String
            Get
                Return ResourceManager.GetString("cc_PK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Poland.
        '''</summary>
        Friend Shared ReadOnly Property cc_PL() As String
            Get
                Return ResourceManager.GetString("cc_PL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Saint Pierre and Miquelon.
        '''</summary>
        Friend Shared ReadOnly Property cc_PM() As String
            Get
                Return ResourceManager.GetString("cc_PM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pitcairn.
        '''</summary>
        Friend Shared ReadOnly Property cc_PN() As String
            Get
                Return ResourceManager.GetString("cc_PN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Puerto Rico.
        '''</summary>
        Friend Shared ReadOnly Property cc_PR() As String
            Get
                Return ResourceManager.GetString("cc_PR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Palestina.
        '''</summary>
        Friend Shared ReadOnly Property cc_PS() As String
            Get
                Return ResourceManager.GetString("cc_PS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Portugal.
        '''</summary>
        Friend Shared ReadOnly Property cc_PT() As String
            Get
                Return ResourceManager.GetString("cc_PT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Palau.
        '''</summary>
        Friend Shared ReadOnly Property cc_PW() As String
            Get
                Return ResourceManager.GetString("cc_PW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Paraguay.
        '''</summary>
        Friend Shared ReadOnly Property cc_PY() As String
            Get
                Return ResourceManager.GetString("cc_PY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Qatar.
        '''</summary>
        Friend Shared ReadOnly Property cc_QA() As String
            Get
                Return ResourceManager.GetString("cc_QA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ﻿Réunion.
        '''</summary>
        Friend Shared ReadOnly Property cc_RE() As String
            Get
                Return ResourceManager.GetString("cc_RE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Romania.
        '''</summary>
        Friend Shared ReadOnly Property cc_RO() As String
            Get
                Return ResourceManager.GetString("cc_RO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Serbia.
        '''</summary>
        Friend Shared ReadOnly Property cc_RS() As String
            Get
                Return ResourceManager.GetString("cc_RS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Russia.
        '''</summary>
        Friend Shared ReadOnly Property cc_RU() As String
            Get
                Return ResourceManager.GetString("cc_RU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rwanda.
        '''</summary>
        Friend Shared ReadOnly Property cc_RW() As String
            Get
                Return ResourceManager.GetString("cc_RW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Saudi Arabia.
        '''</summary>
        Friend Shared ReadOnly Property cc_SA() As String
            Get
                Return ResourceManager.GetString("cc_SA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Solomon Islands.
        '''</summary>
        Friend Shared ReadOnly Property cc_SB() As String
            Get
                Return ResourceManager.GetString("cc_SB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Seychelles.
        '''</summary>
        Friend Shared ReadOnly Property cc_SC() As String
            Get
                Return ResourceManager.GetString("cc_SC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sudan.
        '''</summary>
        Friend Shared ReadOnly Property cc_SD() As String
            Get
                Return ResourceManager.GetString("cc_SD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sweden.
        '''</summary>
        Friend Shared ReadOnly Property cc_SE() As String
            Get
                Return ResourceManager.GetString("cc_SE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Singapore.
        '''</summary>
        Friend Shared ReadOnly Property cc_SG() As String
            Get
                Return ResourceManager.GetString("cc_SG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Saint Helena.
        '''</summary>
        Friend Shared ReadOnly Property cc_SH() As String
            Get
                Return ResourceManager.GetString("cc_SH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Slovenia.
        '''</summary>
        Friend Shared ReadOnly Property cc_SI() As String
            Get
                Return ResourceManager.GetString("cc_SI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Svalbard and Jan Mayen.
        '''</summary>
        Friend Shared ReadOnly Property cc_SJ() As String
            Get
                Return ResourceManager.GetString("cc_SJ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Slovakia.
        '''</summary>
        Friend Shared ReadOnly Property cc_SK() As String
            Get
                Return ResourceManager.GetString("cc_SK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sierra Leone.
        '''</summary>
        Friend Shared ReadOnly Property cc_SL() As String
            Get
                Return ResourceManager.GetString("cc_SL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to San Marino.
        '''</summary>
        Friend Shared ReadOnly Property cc_SM() As String
            Get
                Return ResourceManager.GetString("cc_SM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Senegal.
        '''</summary>
        Friend Shared ReadOnly Property cc_SN() As String
            Get
                Return ResourceManager.GetString("cc_SN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Somalia.
        '''</summary>
        Friend Shared ReadOnly Property cc_SO() As String
            Get
                Return ResourceManager.GetString("cc_SO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Suriname.
        '''</summary>
        Friend Shared ReadOnly Property cc_SR() As String
            Get
                Return ResourceManager.GetString("cc_SR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sao Tome and Principe.
        '''</summary>
        Friend Shared ReadOnly Property cc_ST() As String
            Get
                Return ResourceManager.GetString("cc_ST", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El Salvador.
        '''</summary>
        Friend Shared ReadOnly Property cc_SV() As String
            Get
                Return ResourceManager.GetString("cc_SV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Syrian Arab Republic.
        '''</summary>
        Friend Shared ReadOnly Property cc_SY() As String
            Get
                Return ResourceManager.GetString("cc_SY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Swaziland.
        '''</summary>
        Friend Shared ReadOnly Property cc_SZ() As String
            Get
                Return ResourceManager.GetString("cc_SZ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Turks and Caicos Islands.
        '''</summary>
        Friend Shared ReadOnly Property cc_TC() As String
            Get
                Return ResourceManager.GetString("cc_TC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chad.
        '''</summary>
        Friend Shared ReadOnly Property cc_TD() As String
            Get
                Return ResourceManager.GetString("cc_TD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to French Southern Territories.
        '''</summary>
        Friend Shared ReadOnly Property cc_TF() As String
            Get
                Return ResourceManager.GetString("cc_TF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Togo.
        '''</summary>
        Friend Shared ReadOnly Property cc_TG() As String
            Get
                Return ResourceManager.GetString("cc_TG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thailand.
        '''</summary>
        Friend Shared ReadOnly Property cc_TH() As String
            Get
                Return ResourceManager.GetString("cc_TH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tajikistan.
        '''</summary>
        Friend Shared ReadOnly Property cc_TJ() As String
            Get
                Return ResourceManager.GetString("cc_TJ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tokelau.
        '''</summary>
        Friend Shared ReadOnly Property cc_TK() As String
            Get
                Return ResourceManager.GetString("cc_TK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Timor-Leste.
        '''</summary>
        Friend Shared ReadOnly Property cc_TL() As String
            Get
                Return ResourceManager.GetString("cc_TL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Turkmenistan.
        '''</summary>
        Friend Shared ReadOnly Property cc_TM() As String
            Get
                Return ResourceManager.GetString("cc_TM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tunisia.
        '''</summary>
        Friend Shared ReadOnly Property cc_TN() As String
            Get
                Return ResourceManager.GetString("cc_TN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tonga.
        '''</summary>
        Friend Shared ReadOnly Property cc_TO() As String
            Get
                Return ResourceManager.GetString("cc_TO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Turkey.
        '''</summary>
        Friend Shared ReadOnly Property cc_TR() As String
            Get
                Return ResourceManager.GetString("cc_TR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Trinidad and Tobago.
        '''</summary>
        Friend Shared ReadOnly Property cc_TT() As String
            Get
                Return ResourceManager.GetString("cc_TT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tuvalu.
        '''</summary>
        Friend Shared ReadOnly Property cc_TV() As String
            Get
                Return ResourceManager.GetString("cc_TV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Taiwan.
        '''</summary>
        Friend Shared ReadOnly Property cc_TW() As String
            Get
                Return ResourceManager.GetString("cc_TW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tanzania.
        '''</summary>
        Friend Shared ReadOnly Property cc_TZ() As String
            Get
                Return ResourceManager.GetString("cc_TZ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ukraine.
        '''</summary>
        Friend Shared ReadOnly Property cc_UA() As String
            Get
                Return ResourceManager.GetString("cc_UA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Uganda.
        '''</summary>
        Friend Shared ReadOnly Property cc_UG() As String
            Get
                Return ResourceManager.GetString("cc_UG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to United States Minor Outlying Islands.
        '''</summary>
        Friend Shared ReadOnly Property cc_UM() As String
            Get
                Return ResourceManager.GetString("cc_UM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to United States.
        '''</summary>
        Friend Shared ReadOnly Property cc_US() As String
            Get
                Return ResourceManager.GetString("cc_US", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Uruguay.
        '''</summary>
        Friend Shared ReadOnly Property cc_UY() As String
            Get
                Return ResourceManager.GetString("cc_UY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Uzbekistan.
        '''</summary>
        Friend Shared ReadOnly Property cc_UZ() As String
            Get
                Return ResourceManager.GetString("cc_UZ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Holy See.
        '''</summary>
        Friend Shared ReadOnly Property cc_VA() As String
            Get
                Return ResourceManager.GetString("cc_VA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Saint Vincent and the Grenadines.
        '''</summary>
        Friend Shared ReadOnly Property cc_VC() As String
            Get
                Return ResourceManager.GetString("cc_VC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Venezuela.
        '''</summary>
        Friend Shared ReadOnly Property cc_VE() As String
            Get
                Return ResourceManager.GetString("cc_VE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to British Virgin Islands.
        '''</summary>
        Friend Shared ReadOnly Property cc_VG() As String
            Get
                Return ResourceManager.GetString("cc_VG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to American Virgin Islands.
        '''</summary>
        Friend Shared ReadOnly Property cc_VI() As String
            Get
                Return ResourceManager.GetString("cc_VI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Viet Nam.
        '''</summary>
        Friend Shared ReadOnly Property cc_VN() As String
            Get
                Return ResourceManager.GetString("cc_VN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vanuatu.
        '''</summary>
        Friend Shared ReadOnly Property cc_VU() As String
            Get
                Return ResourceManager.GetString("cc_VU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wallis and Futuna.
        '''</summary>
        Friend Shared ReadOnly Property cc_WF() As String
            Get
                Return ResourceManager.GetString("cc_WF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Samoa.
        '''</summary>
        Friend Shared ReadOnly Property cc_WS() As String
            Get
                Return ResourceManager.GetString("cc_WS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Yemen.
        '''</summary>
        Friend Shared ReadOnly Property cc_YE() As String
            Get
                Return ResourceManager.GetString("cc_YE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mayotte.
        '''</summary>
        Friend Shared ReadOnly Property cc_YT() As String
            Get
                Return ResourceManager.GetString("cc_YT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to South Africa.
        '''</summary>
        Friend Shared ReadOnly Property cc_ZA() As String
            Get
                Return ResourceManager.GetString("cc_ZA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zambia.
        '''</summary>
        Friend Shared ReadOnly Property cc_ZM() As String
            Get
                Return ResourceManager.GetString("cc_ZM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zimbabwe.
        '''</summary>
        Friend Shared ReadOnly Property cc_ZW() As String
            Get
                Return ResourceManager.GetString("cc_ZW", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
