'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Caps.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} is not supported by {1}.
        '''</summary>
        Friend ReadOnly Property err_PropertyIsNotSupported() As String
            Get
                Return ResourceManager.GetString("err_PropertyIsNotSupported", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Property {0} on {1} is read-only.
        '''</summary>
        Friend ReadOnly Property err_PropertyIsReadOnly() As String
            Get
                Return ResourceManager.GetString("err_PropertyIsReadOnly", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sizes of cap images stored in databse. Use 0 for original image size..
        '''</summary>
        Friend ReadOnly Property stg_Images_CapsInDatabase() As String
            Get
                Return ResourceManager.GetString("stg_Images_CapsInDatabase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sizes of cap images stored in file system. Use 0 for original imnage size..
        '''</summary>
        Friend ReadOnly Property stg_Images_CapsInFileSystem() As String
            Get
                Return ResourceManager.GetString("stg_Images_CapsInFileSystem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Defines where images of cap signs are stored. Use &apos;filesystem&apos; for filesystem and &apos;database&apos; for database..
        '''</summary>
        Friend ReadOnly Property stg_Images_CapsSignStorage() As String
            Get
                Return ResourceManager.GetString("stg_Images_CapsSignStorage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Defines where images of cap types are stored. Use &apos;filesystem&apos; for filesystem and &apos;database&apos; for database..
        '''</summary>
        Friend ReadOnly Property stg_Images_CapTypeStorage() As String
            Get
                Return ResourceManager.GetString("stg_Images_CapTypeStorage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Defines where images of main types are stored. Use &apos;filesystem&apos; for filesystem and &apos;database&apos; for database..
        '''</summary>
        Friend ReadOnly Property stg_Images_MainTypeStorage() As String
            Get
                Return ResourceManager.GetString("stg_Images_MainTypeStorage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Defines where images of shapes are stored. Use &apos;filesystem&apos; for filesystem and &apos;database&apos; for database..
        '''</summary>
        Friend ReadOnly Property stg_Images_ShapeStorage() As String
            Get
                Return ResourceManager.GetString("stg_Images_ShapeStorage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Defines where images of storages are stored. Use &apos;filesystem&apos; for filesystem and &apos;database&apos; for database..
        '''</summary>
        Friend ReadOnly Property stg_Images_StorageStorage() As String
            Get
                Return ResourceManager.GetString("stg_Images_StorageStorage", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
