ALTER TABLE [dbo].[Settings]
    ADD CONSTRAINT [UNQ_Settings_Key] UNIQUE NONCLUSTERED ([Key] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

