ALTER TABLE [dbo].[CapType]
    ADD CONSTRAINT [PK_CapType] PRIMARY KEY CLUSTERED ([CapTypeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

