ALTER TABLE [dbo].[Cap_Category_Int]
    ADD CONSTRAINT [PK_Cap_Category_Int] PRIMARY KEY CLUSTERED ([CapID] ASC, [CategoryID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

