ALTER TABLE [dbo].[CapSign]
    ADD CONSTRAINT [PK_CapSign] PRIMARY KEY CLUSTERED ([CapSignID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

