ALTER TABLE [dbo].[CapInstance]
    ADD CONSTRAINT [PK_CapInstance] PRIMARY KEY CLUSTERED ([CapInstanceID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

