ALTER TABLE [dbo].[Cap_CapSign_Int]
    ADD CONSTRAINT [PK_Cap_CapSign_Int] PRIMARY KEY CLUSTERED ([CapID] ASC, [CapSignID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

