ALTER TABLE [dbo].[ISO 3166-1]
    ADD CONSTRAINT [PK_ISO 3166-1] PRIMARY KEY CLUSTERED ([Alpha-2] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

