ALTER TABLE [dbo].[Keyword]
    ADD CONSTRAINT [PK_Keyword] PRIMARY KEY CLUSTERED ([KeywordID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

