ALTER TABLE [dbo].[Material]
    ADD CONSTRAINT [PK_Material] PRIMARY KEY CLUSTERED ([MaterialID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

