ALTER TABLE [dbo].[MainType]
    ADD CONSTRAINT [PK_MainType] PRIMARY KEY CLUSTERED ([MainTypeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

