ALTER TABLE [dbo].[Romanization]
    ADD CONSTRAINT [PK_Romanization] PRIMARY KEY CLUSTERED ([Character] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

