ALTER TABLE [dbo].[Storage]
    ADD CONSTRAINT [PK_Storage] PRIMARY KEY CLUSTERED ([StorageID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

