ALTER TABLE [dbo].[Shape]
    ADD CONSTRAINT [PK_Shape] PRIMARY KEY CLUSTERED ([ShapeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

