ALTER TABLE [dbo].[StorageType]
    ADD CONSTRAINT [PK_StorageType] PRIMARY KEY CLUSTERED ([StorageTypeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

