ALTER TABLE [dbo].[ProductType]
    ADD CONSTRAINT [UNQ_ProductTypeName] UNIQUE NONCLUSTERED ([ProductTypeName] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

