ALTER TABLE [dbo].[Storage]
    ADD CONSTRAINT [UNQ_StorageNumber] UNIQUE NONCLUSTERED ([StorageID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

