ALTER TABLE [dbo].[ISO 3166-1]
    ADD CONSTRAINT [UNQ_ISO 3166-1_Alpha-3] UNIQUE NONCLUSTERED ([Alpha-3] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

