ALTER TABLE [dbo].[Company]
    ADD CONSTRAINT [UNQ_CompanyName] UNIQUE NONCLUSTERED ([CompanyName] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

