ALTER TABLE [dbo].[Image]
    ADD CONSTRAINT [UNQ_Image_RelativePath] UNIQUE NONCLUSTERED ([RelativePath] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

